type Task {
  id: Int!
  phaseId: Int!
  title: String!
  description: String!
  statusId: Int!
  status: Status!
}

type Status {
  id: Int!
  name: String!
}

type Query {
  getTasks(phaseId: Int!): [Task!]!
  getTask(taskId: Int!): Task!
}

type Mutation {
  createTask(phaseId: Int!, title: String!, description: String): Boolean!
  completeTask(taskId: Int!): Boolean!
  reopenTask(taskId: Int!): Boolean!
}
