type Task {
  id: Int!
  phaseId: Int!
  title: String!
  description: String!
  completed: Boolean!
}

type Query {
  getTasks(phaseId: Int!): [Task!]!
  getTask(taskId: Int!): Task!
}

type Mutation {
  createTask(phaseId: Int!, title: String!, description: String): Boolean!
  completeTask(taskId: Int!): Boolean!
}
