type Task {
  id: ID!
  phaseId: ID!
  title: String!
  description: String!
  completed: Boolean!
}

type Query {
  getTasks(phaseId: ID!): [Task!]!
  getTask(taskId: ID!): Task!
}

type Mutation {
  createTask(phaseId: ID!, title: String!, description: String): Boolean!
  completeTask(taskId: ID!): Boolean!
}
