type Article {
  """ UUID identifier """
  id: ID!
  """ UUID of author """
  authorId: ID!
  authorUsername: String!
  title: String!
  """ Short brief of the content """
  perex: String!
  content: String!
  createdAt: String!
  updatedAt: String!
  commentCount: Int!
}

type Query {
  getArticles(limit: Int): [Article!]!
  getArticle(articleId: ID!): Article!
}

type Mutation {
  createArticle(title: String!, perex: String!, content: String!): Article!
  updateArticle(articleId: ID!, title: String, perex: String, content: String): Article!
  deleteArticle(articleId: ID!): Boolean
}
