type Phase {
  id: ID!
  name: String!
  completed: Boolean!
  tasks: [Task]!
}

type Query {
  getPhases(limit: Int): [Phase!]!
  getPhase(phaseId: ID!): Phase!
}

type Mutation {
  createPhase(name: String!): Boolean
  updatePhase(phaseId: ID!, name: String!): Boolean
  deletePhase(phaseId: ID!): Boolean
}
