type Phase {
  id: Int!
  name: String!
  completed: Boolean!
  tasks: [Task]!
}

type Query {
  getPhases(limit: Int): [Phase!]!
  getPhase(phaseId: Int!): Phase!
}

type Mutation {
  createPhase(name: String!): Boolean
  updatePhase(phaseId: Int!, name: String!): Boolean
  deletePhase(phaseId: Int!): Boolean
}
